return {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    event = { 'VeryLazy' },
    enabled = true,
    opts = {
        highlight = {
            enable = true,
            disable = function(_, buf)
                local max_filesize = 100 * 1024 -- 100 Kb limit
                local ok, stats = pcall(vim.uv.fs_stat, vim.api.nvim_buf_get_name(buf))
                if ok and stats and stats.size > max_filesize then
                    return true
                end
            end,
        },
        indent = { enable = true },
        ensure_installed = {
            'awk',
            'bash',
            'bibtex',
            'c',
            'c_sharp',
            'clojure',
            'cmake',
            'comment',
            'commonlisp',
            'cpp',
            'css',
            'csv',
            'diff',
            'dockerfile',
            'fish',
            'git_config',
            'git_rebase',
            'gitattributes',
            'gitcommit',
            'gitignore',
            'go',
            'haskell',
            'html',
            'http',
            'ini',
            'java',
            'javascript',
            'jq',
            'jsdoc',
            'json',
            'json5',
            'kotlin',
            'latex',
            'llvm',
            'lua',
            'make',
            'markdown',
            'markdown_inline',
            'objdump',
            'pascal',
            'perl',
            'php',
            'python',
            'regex',
            'ruby',
            'rust',
            'scheme',
            'scss',
            'sql',
            'ssh_config',
            'toml',
            'tsv',
            'typescript',
            'vim',
            'vimdoc',
            'vue',
            'xml',
            'yaml',
        },
    },
    main = 'nvim-treesitter.configs',
}
