return {
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        event = { 'VeryLazy' },
        opts = {
            highlight = { enable = true },
            indent = { enable = true },
            ensure_installed = {
                'awk',
                'bash',
                'bibtex',
                'c',
                'c_sharp',
                'clojure',
                'cmake',
                'comment',
                'commonlisp',
                'cpp',
                'css',
                'csv',
                'diff',
                'dockerfile',
                'fish',
                'git_config',
                'git_rebase',
                'gitattributes',
                'gitcommit',
                'gitignore',
                'go',
                'haskell',
                'html',
                'ini',
                'java',
                'javascript',
                'jq',
                'jsdoc',
                'json',
                'json5',
                'kotlin',
                'latex',
                'llvm',
                'lua',
                'make',
                'markdown',
                'markdown_inline',
                'objdump',
                'pascal',
                'perl',
                'php',
                'python',
                'regex',
                'ruby',
                'rust',
                'scheme',
                'scss',
                'sql',
                'ssh_config',
                'toml',
                'tsv',
                'typescript',
                'vim',
                'vimdoc',
                'vue',
                'xml',
                'yaml',
            },
        },
        main = 'nvim-treesitter.configs',
    },
    {
        'nvim-treesitter/nvim-treesitter-textobjects',
        dependencies = { 'nvim-treesitter/nvim-treesitter' },
        -- TODO: configure this
    },
}
